data_dir: data2/
images_dir: images/
vcfs_list: data2/chr.list
ids_file: data2/EUR_SAMPLES_ID.txt
anno_file: data2/gencode.v37.annotation.gtf
gmt_file: data2/h.all.v2023.1.Hs.symbols.gmt

use_causal_snps: True
causal_pathways: data2/pathways.csv
causal_snps: data2/snps.txt

maf_filter: 0.05
causal_maf_min: 0.05 
causal_maf_max: 0.20

N: 5000

K: 10
k: 5
gen_var: 0.5
h2s: 0.5
shared: 0.5
m_beta: 0.05
sd_beta: 0.02

causal_id: ph_sperm
sim_id: XXX
pattern: chr
draw_flag: True