data_dir: data
images_dir: images
vcfs_list: chr.list
ids_file: EUR_SAMPLES_ID.txt
anno_file: gencode.v37.annotation.gtf
gmt_data: h.all.v2023.1.Hs.symbols.gmt
pathways: pathways.csv
maf_filter: 0.05
N: 5000
phenos_id: ph_sperm
sim_id: XXX
K: 10
k: 5
gen_var: 0.5
h2s: 0.5
shared: 0.5
m_beta: 0.05
sd_beta: 0.02
draw_flag: True