data_dir: data2
images_dir: images
vcfs_list: chr.list
ids_file: EUR_SAMPLES_ID.txt
anno_file: gencode.v37.annotation.gtf
gmt_data: h.all.v2023.1.Hs.symbols.gmt
snps_provided: True
pathways: pathways.csv
snps: snps.txt
maf_filter: 0.05
causal_maf_min: 0.05 
causal_maf_max: 0.20
N: 5000
phenos_id: ph_sperm
sim_id: XXX
K: 10
k: 5
gen_var: 0.5
h2s: 0.5
shared: 0.5
m_beta: 0.05
sd_beta: 0.02
draw_flag: True